version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks: 
      my-network:
        ipv4_address: 172.18.0.100
  kafka:
    # build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.101
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - zookeeper
    networks: 
      my-network:
        ipv4_address: 172.18.0.101

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks: 
      my-network:
        ipv4_address: 172.18.0.2

  config-service:
    image: yong7317/config-service:1.0
    ports:
      - "8888:8888"
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.profiles.active: default
    depends_on: 
      - rabbitmq
    networks: 
      my-network:
        ipv4_address: 172.18.0.3
  
  discovery-service:
    image: yong7317/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      spring.cloud.config.uri: http://config-service:8888
    depends_on: 
      - config-service
    networks: 
      my-network:
        ipv4_address: 172.18.0.4
  
  apigateway-service:
    image: yong7317/apigateway-service:1.0
    ports:
      - "8000:8000"
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
    depends_on: 
      - discovery-service
    networks: 
      my-network:
        ipv4_address: 172.18.0.5

  mariadb:
    image: yong7317/my-mariadb:1.0
    ports:
      - "13306:3306"
    networks: 
      my-network:
        ipv4_address: 172.18.0.6

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks: 
      my-network:
        ipv4_address: 172.18.0.7
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - C:\prometheus-2.40.2.windows-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      my-network:
        ipv4_address: 172.18.0.8

  grafana:
    image: grafana/grafana 
    ports:
      - "3000:3000"
    networks: 
      my-network:
        ipv4_address: 172.18.0.9

  user-service:
    image: yong7317/user-service:1.0
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      logging.file: /api-logs/users-ws.log
    depends_on: 
      - apigateway-service
    networks: 
      my-network:
        ipv4_address: 172.18.0.12

  order-service:
    image: yong7317/order-service:1.0
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      spring.datasource.url: jdbc:mariadb://mariadb:3306/mydb
      logging.file: /api-logs/orders-ws.log
    depends_on: 
      - apigateway-service
    networks: 
      my-network:
        ipv4_address: 172.18.0.13

  catalog-service:
    image: yong7317/catalog-service:1.0
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      logging.file: /api-logs/catalogs-ws.log
    depends_on: 
      - apigateway-service
    networks: 
      my-network:
        ipv4_address: 172.18.0.14

networks: 
  my-network:
    external: true
    name: ecommerce-network